version: 2
jobs:
  build_and_test_logback_access_spring_boot_starter:
    docker:
      - image: "circleci/openjdk:8"
        environment:
          _JAVA_OPTIONS: "-Xmx1536m"
    working_directory: "~/logback-access-spring-boot-starter/logback-access-spring-boot-starter"
    steps:
      - checkout:
          path: "~/logback-access-spring-boot-starter"
      - restore_cache:
          key: &logback_access_spring_boot_starter_dependencies_cache_key >-
            logback-access-spring-boot-starter-dependencies
            {{ checksum "pom.xml" }}
            {{ checksum ".mvn/wrapper/maven-wrapper.properties" }}
      - run:
          name: "Building and testing"
          command: "./mvnw --batch-mode clean install"
      - save_cache:
          key: *logback_access_spring_boot_starter_dependencies_cache_key
          paths:
            - "~/.m2"
      - run:
          name: "Upload Codecov reports"
          command: "curl --silent https://codecov.io/bash | bash"
      - store_test_results:
          path: "target/surefire-reports"
      - store_artifacts:
          path: "target"
          destination: "/"
      - persist_to_workspace:
          root: &logback_access_spring_boot_starter_workspace_root >-
            ~/.m2/repository/net/rakugakibox/spring/boot/logback-access-spring-boot-starter
          paths:
            - "*"
            - "*/*"
  build_logback_access_spring_boot_starter_sample_jetty:
    docker:
      - image: "circleci/openjdk:8"
        environment:
          _JAVA_OPTIONS: "-Xmx1536m"
    working_directory: "~/logback-access-spring-boot-starter/logback-access-spring-boot-starter-sample-jetty"
    steps:
      - checkout:
          path: "~/logback-access-spring-boot-starter"
      - restore_cache:
          key: &logback_access_spring_boot_starter_sample_jetty_dependencies_cache_key >-
            logback-access-spring-boot-starter-sample-jetty-dependencies
            {{ checksum "pom.xml" }}
            {{ checksum ".mvn/wrapper/maven-wrapper.properties" }}
      - attach_workspace:
          at: *logback_access_spring_boot_starter_workspace_root
      - run:
          name: "Building"
          command: "./mvnw --batch-mode clean install"
      - save_cache:
          key: *logback_access_spring_boot_starter_sample_jetty_dependencies_cache_key
          paths:
            - "~/.m2"
  build_logback_access_spring_boot_starter_sample_tomcat:
    docker:
      - image: "circleci/openjdk:8"
        environment:
          _JAVA_OPTIONS: "-Xmx1536m"
    working_directory: "~/logback-access-spring-boot-starter/logback-access-spring-boot-starter-sample-tomcat"
    steps:
      - checkout:
          path: "~/logback-access-spring-boot-starter"
      - restore_cache:
          key: &logback_access_spring_boot_starter_sample_tomcat_dependencies_cache_key >-
            logback-access-spring-boot-starter-sample-tomcat-dependencies
            {{ checksum "pom.xml" }}
            {{ checksum ".mvn/wrapper/maven-wrapper.properties" }}
      - attach_workspace:
          at: *logback_access_spring_boot_starter_workspace_root
      - run:
          name: "Building"
          command: "./mvnw --batch-mode clean install"
      - save_cache:
          key: *logback_access_spring_boot_starter_sample_tomcat_dependencies_cache_key
          paths:
            - "~/.m2"
  build_logback_access_spring_boot_starter_sample_undertow:
    docker:
      - image: "circleci/openjdk:8"
        environment:
          _JAVA_OPTIONS: "-Xmx1536m"
    working_directory: "~/logback-access-spring-boot-starter/logback-access-spring-boot-starter-sample-undertow"
    steps:
      - checkout:
          path: "~/logback-access-spring-boot-starter"
      - restore_cache:
          key: &logback_access_spring_boot_starter_sample_undertow_dependencies_cache_key >-
            logback-access-spring-boot-starter-sample-undertow-dependencies
            {{ checksum "pom.xml" }}
            {{ checksum ".mvn/wrapper/maven-wrapper.properties" }}
      - attach_workspace:
          at: *logback_access_spring_boot_starter_workspace_root
      - run:
          name: "Building"
          command: "./mvnw --batch-mode clean install"
      - save_cache:
          key: *logback_access_spring_boot_starter_sample_undertow_dependencies_cache_key
          paths:
            - "~/.m2"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test_logback_access_spring_boot_starter
      - build_logback_access_spring_boot_starter_sample_jetty:
          requires:
            - build_and_test_logback_access_spring_boot_starter
      - build_logback_access_spring_boot_starter_sample_tomcat:
          requires:
            - build_and_test_logback_access_spring_boot_starter
      - build_logback_access_spring_boot_starter_sample_undertow:
          requires:
            - build_and_test_logback_access_spring_boot_starter
