version: 2
aliases:
  - &java_container
    image: "circleci/openjdk:8"
    environment:
      _JAVA_OPTIONS: "-Xmx1536m"
  - &logback_access_spring_boot_starter_dependencies_cache_key >-
    logback-access-spring-boot-starter-dependencies
    {{ checksum "pom.xml" }}
    {{ checksum ".mvn/wrapper/maven-wrapper.properties" }}
  - &logback_access_spring_boot_starter_sample_jetty_dependencies_cache_key >-
    logback-access-spring-boot-starter-sample-jetty-dependencies
    {{ checksum "pom.xml" }}
    {{ checksum ".mvn/wrapper/maven-wrapper.properties" }}
  - &logback_access_spring_boot_starter_sample_tomcat_dependencies_cache_key >-
    logback-access-spring-boot-starter-sample-tomcat-dependencies
    {{ checksum "pom.xml" }}
    {{ checksum ".mvn/wrapper/maven-wrapper.properties" }}
  - &logback_access_spring_boot_starter_sample_undertow_dependencies_cache_key >-
    logback-access-spring-boot-starter-sample-undertow-dependencies
    {{ checksum "pom.xml" }}
    {{ checksum ".mvn/wrapper/maven-wrapper.properties" }}
  - &checkout
    checkout:
      path: "~/logback-access-spring-boot-starter"
  - &attach_workspace
    attach_workspace:
      at: "~/logback-access-spring-boot-starter-workspace"
  - &restore_from_workspace
    run:
      name: "Restoring from workspace"
      command: "cp --archive --verbose ~/logback-access-spring-boot-starter-workspace/. ~"
jobs:
  build_logback_access_spring_boot_starter:
    docker:
      - *java_container
    working_directory: "~/logback-access-spring-boot-starter/logback-access-spring-boot-starter"
    steps:
      - *checkout
      - restore_cache:
          key: *logback_access_spring_boot_starter_dependencies_cache_key
      - run:
          name: "Building and testing"
          command: "./mvnw --batch-mode clean install"
      - save_cache:
          key: *logback_access_spring_boot_starter_dependencies_cache_key
          paths:
            - "~/.m2"
      - run:
          name: "Uploading Codecov reports"
          command: "curl --silent https://codecov.io/bash | bash"
      - store_test_results:
          path: "target/surefire-reports"
      - store_artifacts:
          path: "target"
          destination: "/"
      - persist_to_workspace:
          root: "~"
          paths:
            - ".m2/repository/net/rakugakibox/spring/boot/logback-access-spring-boot-starter"
  build_logback_access_spring_boot_starter_sample_jetty:
    docker:
      - *java_container
    working_directory: "~/logback-access-spring-boot-starter/logback-access-spring-boot-starter-sample-jetty"
    steps:
      - *checkout
      - *attach_workspace
      - *restore_from_workspace
      - restore_cache:
          key: *logback_access_spring_boot_starter_sample_jetty_dependencies_cache_key
      - run:
          name: "Building"
          command: "./mvnw --batch-mode clean install"
      - save_cache:
          key: *logback_access_spring_boot_starter_sample_jetty_dependencies_cache_key
          paths:
            - "~/.m2"
  build_logback_access_spring_boot_starter_sample_tomcat:
    docker:
      - *java_container
    working_directory: "~/logback-access-spring-boot-starter/logback-access-spring-boot-starter-sample-tomcat"
    steps:
      - *checkout
      - *attach_workspace
      - *restore_from_workspace
      - restore_cache:
          key: *logback_access_spring_boot_starter_sample_tomcat_dependencies_cache_key
      - run:
          name: "Building"
          command: "./mvnw --batch-mode clean install"
      - save_cache:
          key: *logback_access_spring_boot_starter_sample_tomcat_dependencies_cache_key
          paths:
            - "~/.m2"
  build_logback_access_spring_boot_starter_sample_undertow:
    docker:
      - *java_container
    working_directory: "~/logback-access-spring-boot-starter/logback-access-spring-boot-starter-sample-undertow"
    steps:
      - *checkout
      - *attach_workspace
      - *restore_from_workspace
      - restore_cache:
          key: *logback_access_spring_boot_starter_sample_undertow_dependencies_cache_key
      - run:
          name: "Building"
          command: "./mvnw --batch-mode clean install"
      - save_cache:
          key: *logback_access_spring_boot_starter_sample_undertow_dependencies_cache_key
          paths:
            - "~/.m2"
workflows:
  version: 2
  build:
    jobs:
      - build_logback_access_spring_boot_starter
      - build_logback_access_spring_boot_starter_sample_jetty:
          requires:
            - build_logback_access_spring_boot_starter
      - build_logback_access_spring_boot_starter_sample_tomcat:
          requires:
            - build_logback_access_spring_boot_starter
      - build_logback_access_spring_boot_starter_sample_undertow:
          requires:
            - build_logback_access_spring_boot_starter
