version: 2
jobs:
  build-and-test-logback-access-spring-boot-starter:
    docker:
      - image: "circleci/openjdk:8"
    environment:
        _JAVA_OPTIONS: "-Xmx1536m"
    working_directory: "~/logback-access-spring-boot-starter/logback-access-spring-boot-starter"
    steps:
      - checkout:
          path: "~/logback-access-spring-boot-starter"
      - restore_cache:
          key: 'logback-access-spring-boot-starter-dependencies-{{ checksum "pom.xml" }}'
      - run:
          name: "Building and testing"
          command: "./mvnw --batch-mode clean install"
      - save_cache:
          key: 'logback-access-spring-boot-starter-dependencies-{{ checksum "pom.xml" }}'
          paths:
            - "~/.m2"
      - store_test_results:
          path: "target/surefire-reports"
      - run:
          name: "Upload Codecov reports"
          command: "curl --silent https://codecov.io/bash | bash"
      - store_artifacts:
          path: "target"
          destination: "/"
      - persist_to_workspace:
          root: "~/.m2/repository/net/rakugakibox/spring/boot/logback-access-spring-boot-starter"
          paths:
            - "*"
            - "*/*"
  build-logback-access-spring-boot-starter-sample-jetty:
    docker:
      - image: "circleci/openjdk:8"
    environment:
        _JAVA_OPTIONS: "-Xmx1536m"
    working_directory: "~/logback-access-spring-boot-starter/logback-access-spring-boot-starter-sample-jetty"
    steps:
      - checkout:
          path: "~/logback-access-spring-boot-starter"
      - restore_cache:
          key: 'logback-access-spring-boot-starter-sample-jetty-dependencies-{{ checksum "pom.xml" }}'
      - attach_workspace:
          at: "~/.m2/repository/net/rakugakibox/spring/boot/logback-access-spring-boot-starter"
      - run:
          name: "Building"
          command: "./mvnw --batch-mode clean install"
      - save_cache:
          key: 'logback-access-spring-boot-starter-sample-jetty-dependencies-{{ checksum "pom.xml" }}'
          paths:
            - "~/.m2"
  build-logback-access-spring-boot-starter-sample-tomcat:
    docker:
      - image: "circleci/openjdk:8"
    environment:
        _JAVA_OPTIONS: "-Xmx1536m"
    working_directory: "~/logback-access-spring-boot-starter/logback-access-spring-boot-starter-sample-tomcat"
    steps:
      - checkout:
          path: "~/logback-access-spring-boot-starter"
      - restore_cache:
          key: 'logback-access-spring-boot-starter-sample-tomcat-dependencies-{{ checksum "pom.xml" }}'
      - attach_workspace:
          at: "~/.m2/repository/net/rakugakibox/spring/boot/logback-access-spring-boot-starter"
      - run:
          name: "Building"
          command: "./mvnw --batch-mode clean install"
      - save_cache:
          key: 'logback-access-spring-boot-starter-sample-tomcat-dependencies-{{ checksum "pom.xml" }}'
          paths:
            - "~/.m2"
  build-logback-access-spring-boot-starter-sample-undertow:
    docker:
      - image: "circleci/openjdk:8"
    environment:
        _JAVA_OPTIONS: "-Xmx1536m"
    working_directory: "~/logback-access-spring-boot-starter/logback-access-spring-boot-starter-sample-undertow"
    steps:
      - checkout:
          path: "~/logback-access-spring-boot-starter"
      - restore_cache:
          key: 'logback-access-spring-boot-starter-sample-undertow-dependencies-{{ checksum "pom.xml" }}'
      - attach_workspace:
          at: "~/.m2/repository/net/rakugakibox/spring/boot/logback-access-spring-boot-starter"
      - run:
          name: "Building"
          command: "./mvnw --batch-mode clean install"
      - save_cache:
          key: 'logback-access-spring-boot-starter-sample-undertow-dependencies-{{ checksum "pom.xml" }}'
          paths:
            - "~/.m2"
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test-logback-access-spring-boot-starter
      - build-logback-access-spring-boot-starter-sample-jetty:
          requires:
            - build-and-test-logback-access-spring-boot-starter
      - build-logback-access-spring-boot-starter-sample-tomcat:
          requires:
            - build-and-test-logback-access-spring-boot-starter
      - build-logback-access-spring-boot-starter-sample-undertow:
          requires:
            - build-and-test-logback-access-spring-boot-starter
